# Generated by Django 4.1.5 on 2023-02-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amt',
            new_name='sell_amt',
        ),
        migrations.AddField(
            model_name='item',
            name='limited_edition',
            field=models.BooleanField(default=None, verbose_name='Limited edition'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Product img name')),
                ('img', models.ImageField(upload_to='files/item_img/', verbose_name='Product Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.item')),
            ],
        ),
    ]
