# Generated by Django 4.1.5 on 2023-02-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_rename_amt_item_sell_amt_item_limited_edition_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Item in stock'),
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_market.item'),
        ),
    ]
