# Generated by Django 4.1.5 on 2023-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0003_item_in_stock_review_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.IntegerField(null=True, verbose_name='Item Image'),
        ),
        migrations.DeleteModel(
            name='ItemImg',
        ),
    ]
