# Generated by Django 4.1.5 on 2023-02-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0004_item_img_delete_itemimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Item Image'),
        ),
    ]
