# Generated by Django 4.1.5 on 2023-02-15 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0005_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Day of publishing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='files/items/', verbose_name='Item Image'),
        ),
    ]
