# Generated by Django 4.1.5 on 2023-02-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0006_item_published_at_alter_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='other', max_length=30, verbose_name='Product category')),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_market.item')),
            ],
        ),
    ]
