# Generated by Django 4.1.5 on 2023-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0007_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(default=None, null=True, to='app_market.category'),
        ),
    ]
