# Generated by Django 4.1.5 on 2023-02-11 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('phone_numb', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
                ('avatar', models.ImageField(upload_to='files/avatars/', verbose_name='Avatar')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
